SELECT
     mxtrainv.`ITEM` AS mxtrainv_ITEM,
     mxtrainv.`FECHA` AS mxtrainv_FECHA,
     mxtrainv.`TIPOMOV` AS mxtrainv_TIPOMOV,
     mxtrainv.`UNIDAD` AS mxtrainv_UNIDAD,
     mxtrainv.`CANTIDAD` AS mxtrainv_CANTIDAD,
     mxtrainv.`COSTO` AS mxtrainv_COSTO,
     (mxtrainv.`COSTO`+ mxtrainv.`COSTO` * (mxctainv.`ITBM`/100))* mxtrainv.`CANTIDAD` AS mxtrainv_COSTO_TOT,
     mxtrainv.`CANTIDAD` * mxtrainv.`COSTO` AS mxtrainv_COSTO_TOTAL,
     mxtrainv.`NUMDOC` AS mxtrainv_NUMDOC,
     mxtrainv.`FACTURA` AS mxtrainv_FACTURA,
     mxtrainv.`DEPARTAMENTO` AS mxtrainv_DEPARTAMENTO,
     mxtrainv.`ORIGEN` AS mxtrainv_ORIGEN,
     mxtrainv.`ORDEN_COMPRA` AS mxtrainv_ORDEN_COMPRA,
     mxtrainv.`DISPONIBLE` AS mxtrainv_DISPONIBLE,
     mxtrainv.`COMENTARIO` AS mxtrainv_COMENTARIO,
     mxtrainv.`SOLICITADO` AS mxtrainv_SOLICITADO,
     mxencped.`FECHA` AS mxencped_FECHA,
     mxencped.`NUMERO_PEDIDO` AS mxencped_NUMERO_PEDIDO,
     mxencped.`DEPARTAMENTO` AS mxencped_DEPARTAMENTO,
     mxencped.`FECHA_ENTREGA` AS mxencped_FECHA_ENTREGA,
     mxencped.`SUB_TOTAL` AS mxencped_SUB_TOTAL,
     mxencped.`ITBM` AS mxencped_ITBM,
     mxencped.`TOTAL` AS mxencped_TOTAL,
     mxencped.`NUMERO_CASO` AS mxencped_NUMERO_CASO,
     mxctainv.`ITEM` AS mxctainv_ITEM,
     mxctainv.`DESCRIPCION` AS mxctainv_DESCRIPCION,
     mxctainv.`CATEGORIA` AS mxctainv_CATEGORIA,
     mxctainv.`EXMIN` AS mxctainv_EXMIN,
     mxctainv.`UNIDAD` AS mxctainv_UNIDAD,
     mxctainv.`COD_PROVEE` AS mxctainv_COD_PROVEE,
     mxctainv.`ULT_COSTO` AS mxctainv_ULT_COSTO,
     mxctainv.`COSTO_ACT` AS mxctainv_COSTO_ACT,
     mxctainv.`EXISTE_ACT` AS mxctainv_EXISTE_ACT,
     mxctainv.`ACU_ENT` AS mxctainv_ACU_ENT,
     mxctainv.`ACU_COS` AS mxctainv_ACU_COS,
     mxctainv.`FECHA_CREACION` AS mxctainv_FECHA_CREACION,
     mxctainv.`COSTO_ANT` AS mxctainv_COSTO_ANT,
     mxctainv.`ESTATUS` AS mxctainv_ESTATUS,
     mxctainv.`CTA_CONTABLE` AS mxctainv_CTA_CONTABLE,
     mxctainv.`CLASIFICACION` AS mxctainv_CLASIFICACION,
     mxctainv.`UBICACION_FISICA` AS mxctainv_UBICACION_FISICA,
     mxctainv.`ITBM` AS mxctainv_ITBM
FROM
     `mxencped` mxencped INNER JOIN `mxtrainv` mxtrainv ON mxencped.`NUMERO_PEDIDO` = mxtrainv.`NUMDOC`
     INNER JOIN `mxctainv` mxctainv ON mxtrainv.`ITEM` = mxctainv.`ITEM`
WHERE
    mxencped.`NUMERO_PEDIDO` = $P{PEDIDO} AND mxtrainv.`TIPOMOV` = 'SA'